/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrameCYK.java
 *
 * Created on Dec 23, 2014, 1:08:57 PM
 */
package MyFormPackage;

import MyTools.CheckInput;
import MyTools.Tools;
import Mydata.GrammerProperties;
import Mydata.InstructionCheck;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author ali
 */
public class JFrameCYK extends javax.swing.JFrame {

    /**
     * counter index Array List
     */
    int i = 0;
     String Mess = "";
    ArrayList<GrammerProperties> ArrayListGrammer;
    MyTools.CheckInput checkinput;
    Mydata.InstructionCheck checkProduction;
    /**
     * in is varible مقدار دهی می شود که رشته ورودی  جزه حروف الفبا کوچک هست یا نه؟
     */
    boolean in = true;

    /** Creates new form JFrameCYK */
    public JFrameCYK() {
        initComponents();
        jtxtareaPrint.setEditable(false);
        jlblMessStr.setVisible(false);
        jtxtStr.setVisible(false);
        jbtnBarrasyStr.setVisible(false);
        jbtnExit.setVisible(false);
        jbtnNewGrammer.setVisible(false);
        ArrayListGrammer = new ArrayList<GrammerProperties>();
        checkinput = new CheckInput();
        Tools.setFormLocation(this);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtareaPrint = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jbtnAddGrammer = new javax.swing.JButton();
        jbtnEndGrammer = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jlblMessStr = new javax.swing.JLabel();
        jtxtStr = new javax.swing.JTextField();
        jbtnBarrasyStr = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnNewGrammer = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxRight1 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxLeft = new javax.swing.JComboBox();
        jComboBoxRight2 = new javax.swing.JComboBox();
        jtxtAlpba = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CYK الگوریتم");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0)));

        jLabel1.setBackground(new java.awt.Color(51, 255, 0));
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("بسم الله الرحمن الرحیم");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(jLabel1)
                .addContainerGap(253, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel3.setText("کاربر گرامی برای استفاده از این برنامه باید گرامر خود را به فرم چامسکی وارد کنید.");

        jLabel4.setText("فرم چامسکی به صورت رو به رو است.");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/paykan.gif"))); // NOI18N

        jLabel7.setText("AB");

        jLabel13.setText("S");

        jLabel2.setText("یا");

        jLabel8.setText("x");

        jLabel14.setText("S");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/paykan.gif"))); // NOI18N

        jLabel5.setText(" فقط می تواند یک حرف از حروف الفبا باشد.");

        jLabel6.setText("x");

        jtxtareaPrint.setColumns(20);
        jtxtareaPrint.setRows(5);
        jScrollPane1.setViewportView(jtxtareaPrint);

        jLabel9.setText("دستورات گرامر خود را با اشیاء زیر درست کنید.");

        jbtnAddGrammer.setText("اضافه کن");
        jbtnAddGrammer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddGrammerActionPerformed(evt);
            }
        });

        jbtnEndGrammer.setText("اتمام گرامر");
        jbtnEndGrammer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEndGrammerActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jlblMessStr.setText("رشته خود را وارد کنید:");

        jbtnBarrasyStr.setText("بررسی رشته");
        jbtnBarrasyStr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBarrasyStrActionPerformed(evt);
            }
        });

        jbtnExit.setText("خروج");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        jbtnNewGrammer.setText("دریافت گرامر جدید");
        jbtnNewGrammer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNewGrammerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbtnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnBarrasyStr, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnNewGrammer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtStr, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblMessStr)
                .addGap(91, 91, 91))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtStr, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnBarrasyStr, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblMessStr, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnNewGrammer, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0)));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/paykan.gif"))); // NOI18N

        jComboBoxRight1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "S", "A", "B", "C", "D", "E", "F", "G", "H", "K", "M", "N", "O", "P", "R", "T", "U", "W", "X", "Y", "Z" }));

        jLabel11.setText("یا");

        jComboBoxLeft.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "S", "A", "B", "C", "D", "E", "F", "G", "H", "K", "M", "N", "O", "P", "R", "T", "U", "W", "X", "Y", "Z" }));

        jComboBoxRight2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "S", "A", "B", "C", "D", "E", "F", "G", "H", "K", "M", "N", "O", "P", "R", "T", "U", "W", "X", "Y", "Z" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addComponent(jComboBoxLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jComboBoxRight1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jComboBoxRight2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel11)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jtxtAlpba, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(16, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxLeft, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxRight1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxRight2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtAlpba, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel16)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel7)
                            .addGap(32, 32, 32)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel6))
                                .addComponent(jLabel3))
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(67, 67, 67)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnEndGrammer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                            .addComponent(jbtnAddGrammer, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE))
                        .addContainerGap())))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(jLabel2))
                            .addComponent(jLabel7))
                        .addComponent(jLabel16))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel8))
                        .addComponent(jLabel17))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtnAddGrammer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnEndGrammer, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAddGrammerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddGrammerActionPerformed
        /**
         * create new interfase of class GrammerPropertis
         * in pakage MyData
         */
        GrammerProperties e = new GrammerProperties();

        String VariableR = "";
        Mess = "";
        in = true;
        String Alephba = jtxtAlpba.getText().toString();
        Alephba = Alephba.trim();
        if (Alephba.length() == 1) {
            if (checkinput.CheckAlephba(Alephba) == false) {
                Mess = "ترمینال باید فقط یک حرف از حروف الفبا کوچک باشد.";
                jtxtAlpba.setText("");
                in = false;
            }
        }

        if (Alephba.length() > 1 && in) {
            Mess = "ترمینال باید فقط یک حرف از حروف الفبا کوچک باشد.";
            jtxtAlpba.setText("");
            in = false;
        }
        //this:چک می کند که کاربر  دو متغیر انتخاب کند یا اصلا انتخاب نکند
        int indexR1 = jComboBoxRight1.getSelectedIndex();
        int indexR2 = jComboBoxRight2.getSelectedIndex();
        if ((indexR1 == 0 && indexR2 != 0) || (indexR1 != 0 && indexR2 == 0)) {
            Mess += "\n";
            Mess += "متغیرهای سمت راست گرامر یا باید هر دو با هم انتخاب شوند یا هیچ کدام انتخاب نشوند.";
            in = false;
        }
        if (Alephba.length() == 0) {
            if ((indexR1 == 0 && indexR2 == 0)) {
                in = false;
                Mess += "همه فیلد ها نمی توانند خالی باشند.";
            }
            Alephba = "#";
        }



        if (in == false) {
            Mess = Mess.trim();
            JOptionPane.showMessageDialog(null, Mess, "خطا", JOptionPane.ERROR_MESSAGE);
        }
        if (in) {
            e.setAlephba(Alephba);
            e.setLeftVariable(jComboBoxLeft.getSelectedItem().toString().trim());
            VariableR = jComboBoxRight1.getSelectedItem().toString().trim();
            VariableR += jComboBoxRight2.getSelectedItem().toString();
            VariableR = VariableR.trim();
            e.setRightVariable(VariableR);
            /**
             * save data to ArrayList
             */
            ArrayListGrammer.add(i, e);
            /**<b>i++</b>
             * go new index of array
             */
            i++;
            /**
             * print view of Grammer for user
             */
            String Gramer = "";
            if (Alephba.compareTo("#") == 0) {
                Gramer = "   " + jComboBoxLeft.getSelectedItem().toString() + "  --> " + VariableR;
            } else if ((indexR1 == 0 && indexR2 == 0)) {
                Gramer = "   " + jComboBoxLeft.getSelectedItem().toString() + "  --> " + Alephba;
            } else {
                Gramer = "   " + jComboBoxLeft.getSelectedItem().toString() + "  --> " + VariableR + " | " + Alephba;
            }
            jtxtareaPrint.append(Gramer + "\n");

            jtxtAlpba.setText("");
        }
}//GEN-LAST:event_jbtnAddGrammerActionPerformed

    private void jbtnEndGrammerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEndGrammerActionPerformed
        jlblMessStr.setVisible(true);
        jbtnBarrasyStr.setVisible(true);
        jbtnExit.setVisible(true);
        jbtnNewGrammer.setVisible(true);
        jtxtStr.setVisible(true);
        jbtnAddGrammer.setEnabled(false);
        jbtnEndGrammer.setEnabled(false);
}//GEN-LAST:event_jbtnEndGrammerActionPerformed


    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbtnExitActionPerformed
    /**
     *this:بررسی رشته با الگوریتم CYK
     * @param evt
     */
    private void jbtnBarrasyStrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBarrasyStrActionPerformed
        checkProduction = new InstructionCheck(ArrayListGrammer);
        String inputStr = jtxtStr.getText().toString();
        inputStr = inputStr.trim();
        int StrLengh = inputStr.length();
        in = true;
        String SetProduc = "";
        String produc = "";
        String[][] CYK = null;
        if(inputStr.length()!=0){
        if (checkinput.CheckAlephba(inputStr) == false) {
            JOptionPane.showMessageDialog(null, "رشته باید از حروف الفبا کوچک باشد.", "خطا", JOptionPane.ERROR_MESSAGE);
            jtxtStr.setText("");
            in = false;
        }
        }else{
            in=false;
        }
        if (in) {
            CYK = new String[StrLengh][StrLengh];
            for (int k = 0; k < StrLengh; k++) {
                for (int j = 0; j < StrLengh; j++) {
                    CYK[k][j] = "#";
                }
            }
            char[] inputChar = inputStr.toCharArray();
            //this:پر کردن قطر اصلی با متغیرهایی که حروف را تولید می کنند.
            for (int j = 0; j < inputChar.length; j++) {
                CYK[j][j] = checkProduction.CheckProductionsAlephba(inputChar[j] + " ");
            }
            //this:پر کردن قطر ها
            for (int diagonal = 1, col = 1; diagonal < StrLengh; diagonal++) {
                for (int row = 0; row < (StrLengh - diagonal); row++) {
                    col = diagonal + row;
                    for (int k =row; k < col; k++) {
                        produc = checkProduction.Decarty(CYK[row][k], CYK[k + 1][col]);
                        if (produc.compareTo("#") != 0) {
                            SetProduc += produc;
                        }
                    }
                    SetProduc = SetProduc.trim();
                    if(SetProduc.length()==0){
                         CYK[row][col]="Ø";
                    }else{
                    CYK[row][col] = checkProduction.CheckRepitedVariable(SetProduc);
                    }
                    SetProduc="";
                }
            }
       
        boolean P = false;
        CYK[0][StrLengh - 1] = CYK[0][StrLengh - 1].trim();
        String StartState = ArrayListGrammer.get(0).getLeftVariable();
        char[] strFinal = CYK[0][StrLengh - 1].toCharArray();
        for (int j = 0; j < CYK[0][StrLengh - 1].length(); j++) {
            if (StartState.compareTo(String.valueOf(strFinal[j])) == 0) {
                P = true;
                j *= 10;
            }
        }
        
      ClassTable FrameMessage=new ClassTable();
      FrameMessage.setDataTable(CYK, inputStr,P);

    }//end if(in==true)
        jtxtStr.setText("");

    }//GEN-LAST:event_jbtnBarrasyStrActionPerformed

    private void jbtnNewGrammerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNewGrammerActionPerformed
       JFrameCYK JFCYK2=new JFrameCYK();
       JFCYK2.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jbtnNewGrammerActionPerformed
       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JFrameCYK().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxLeft;
    private javax.swing.JComboBox jComboBoxRight1;
    private javax.swing.JComboBox jComboBoxRight2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnAddGrammer;
    private javax.swing.JButton jbtnBarrasyStr;
    private javax.swing.JButton jbtnEndGrammer;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnNewGrammer;
    private javax.swing.JLabel jlblMessStr;
    private javax.swing.JTextField jtxtAlpba;
    private javax.swing.JTextField jtxtStr;
    private javax.swing.JTextArea jtxtareaPrint;
    // End of variables declaration//GEN-END:variables
}
